# nanobrew installation manager
#
# During activation, we create `/opt/nanobrew` by running `nb init`,
# set ownership, and optionally install a declarative list of packages.

{
  pkgs,
  lib,
  config,
  options,
  ...
}:
let
  inherit (lib) types;

  # Support both 'nix-nanobrew' and 'modules.darwin.nanobrew' (for dotfiles style)
  cfg = if config.modules.darwin.nanobrew.enable or false then config.modules.darwin.nanobrew else config.nix-nanobrew;

  nb = cfg.package;

  # Generate the content for the Nanobrew file (Brewfile)
  nanobrewFile = pkgs.writeText "Nanobrew" ''
    # Generated by nix-nanobrew
    ${lib.concatMapStrings (name: "brew \"${name}\"\n") cfg.brews}
    ${lib.concatMapStrings (name: "cask \"${name}\"\n") cfg.casks}
  '';

  setupNanobrew = pkgs.writeShellScript "setup-nanobrew" ''
    set -euo pipefail

    NIX_NANOBREW_UID=$(id -u "${cfg.user}" || (echo "Error: Failed to get UID of ${cfg.user}" >&2; exit 1))
    
    if [[ "$(uname)" == "Darwin" ]]; then
      NIX_NANOBREW_GID=$(dscl . -read "/Groups/${cfg.group}" PrimaryGroupID 2>/dev/null | awk '{print $2}' || id -g "${cfg.user}")
    else
      NIX_NANOBREW_GID=$(getent group "${cfg.group}" | cut -d: -f3 || id -g "${cfg.user}")
    fi

    echo "setting up nanobrew (/opt/nanobrew)..."

    # 1. Initialize nanobrew
    sudo ${nb}/bin/nb init

    # 2. Ensure ownership
    sudo chown -R $NIX_NANOBREW_UID:$NIX_NANOBREW_GID /opt/nanobrew

    # 3. Handle Migration
    ${lib.optionalString cfg.autoMigrate ''
      if [[ -d "/opt/homebrew/Cellar" || -d "/usr/local/Cellar" ]]; then
        echo "Attempting to migrate from Homebrew..."
        sudo -u ${cfg.user} ${nb}/bin/nb migrate || echo "Migration failed or already completed."
      fi
    ''}

    # 4. Declarative Package Installation
    if [[ -f "${nanobrewFile}" ]]; then
      echo "Installing declarative packages..."
      # Run as the target user
      sudo -u ${cfg.user} ${nb}/bin/nb bundle install "${nanobrewFile}"
    fi
  '';

  nanobrewOptions = {
    enable = lib.mkOption {
      description = "Whether to install and configure nanobrew.";
      type = types.bool;
      default = false;
    };
    package = lib.mkOption {
      description = "The nanobrew package to use.";
      type = types.package;
      default = pkgs.callPackage ../pkgs/nanobrew { };
    };
    user = lib.mkOption {
      description = "The user who should own /opt/nanobrew.";
      type = types.str;
    };
    group = lib.mkOption {
      description = "The group that should own /opt/nanobrew.";
      type = types.str;
      default = "admin";
    };
    autoMigrate = lib.mkOption {
      description = "Whether to automatically migrate existing Homebrew installations.";
      type = types.bool;
      default = false;
    };
    brews = lib.mkOption {
      description = "List of formulae to install.";
      type = types.listOf types.str;
      default = [ ];
    };
    casks = lib.mkOption {
      description = "List of casks to install.";
      type = types.listOf types.str;
      default = [ ];
    };
    enableBashIntegration = lib.mkEnableOption "nanobrew bash integration" // {
      default = true;
    };
    enableFishIntegration = lib.mkEnableOption "nanobrew fish integration" // {
      default = true;
    };
    enableZshIntegration = lib.mkEnableOption "nanobrew zsh integration" // {
      default = true;
    };
  };
in
{
  options = {
    nix-nanobrew = nanobrewOptions;
    modules.darwin.nanobrew = nanobrewOptions;
  };

  config = lib.mkIf cfg.enable {
    # Shell integrations: Add /opt/nanobrew/prefix/bin to PATH
    programs.bash.interactiveShellInit = lib.mkIf cfg.enableBashIntegration ''
      export PATH="/opt/nanobrew/prefix/bin:$PATH"
    '';

    programs.zsh.interactiveShellInit = lib.mkIf cfg.enableZshIntegration ''
      export PATH="/opt/nanobrew/prefix/bin:$PATH"
    '';

    programs.fish.interactiveShellInit = lib.mkIf cfg.enableFishIntegration ''
      fish_add_path /opt/nanobrew/prefix/bin
    '';

    environment.systemPackages = [ nb ];

    environment.variables = {
      NANOBREW_PREFIX = "/opt/nanobrew/prefix";
    };

    system.activationScripts.setup-nanobrew = {
      supportsDryRun = false;
      text = ''
        ${setupNanobrew}
      '';
    };

    # Bypass nix-darwin's Homebrew installation check if we are managing it.
    system.checks.text = lib.mkIf (config.homebrew.enable or false) (
      lib.mkBefore ''
        # Ignore unused variable in nix-darwin versions without it
        # shellcheck disable=SC2034
        INSTALLING_HOMEBREW=1
      ''
    );
  };
}
